package com.ouran.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFen<M extends BaseFen<M>> extends Model<M> implements IBean {

	public M setUserid(java.lang.Integer userid) {
		set("userid", userid);
		return (M)this;
	}
	
	public java.lang.Integer getUserid() {
		return getInt("userid");
	}

	public M setFenid(java.lang.Integer fenid) {
		set("fenid", fenid);
		return (M)this;
	}
	
	public java.lang.Integer getFenid() {
		return getInt("fenid");
	}

}
