package com.ouran.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWenji<M extends BaseWenji<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setUserid(java.lang.Integer userid) {
		set("userid", userid);
		return (M)this;
	}
	
	public java.lang.Integer getUserid() {
		return getInt("userid");
	}

	public M setPic(java.lang.String pic) {
		set("pic", pic);
		return (M)this;
	}
	
	public java.lang.String getPic() {
		return getStr("pic");
	}

	public M setTuwenNum(java.lang.Integer tuwenNum) {
		set("tuwen_num", tuwenNum);
		return (M)this;
	}
	
	public java.lang.Integer getTuwenNum() {
		return getInt("tuwen_num");
	}

}
