package com.ouran.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTuwen<M extends BaseTuwen<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setPic(java.lang.String pic) {
		set("pic", pic);
		return (M)this;
	}
	
	public java.lang.String getPic() {
		return getStr("pic");
	}

	public M setWriter(java.lang.String writer) {
		set("writer", writer);
		return (M)this;
	}
	
	public java.lang.String getWriter() {
		return getStr("writer");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public M setUser(java.lang.String user) {
		set("user", user);
		return (M)this;
	}
	
	public java.lang.String getUser() {
		return getStr("user");
	}

	public M setLikes(java.lang.Integer likes) {
		set("likes", likes);
		return (M)this;
	}
	
	public java.lang.Integer getLikes() {
		return getInt("likes");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

	public M setIsoriginal(java.lang.Integer isoriginal) {
		set("isoriginal", isoriginal);
		return (M)this;
	}
	
	public java.lang.Integer getIsoriginal() {
		return getInt("isoriginal");
	}

}
