package com.ouran.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLikes<M extends BaseLikes<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setTuwenid(java.lang.Integer tuwenid) {
		set("tuwenid", tuwenid);
		return (M)this;
	}
	
	public java.lang.Integer getTuwenid() {
		return getInt("tuwenid");
	}

	public M setTopicid(java.lang.Integer topicid) {
		set("topicid", topicid);
		return (M)this;
	}
	
	public java.lang.Integer getTopicid() {
		return getInt("topicid");
	}

}
