package com.ouran.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMusic<M extends BaseMusic<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setPath(java.lang.String path) {
		set("path", path);
		return (M)this;
	}
	
	public java.lang.String getPath() {
		return getStr("path");
	}

	public M setLikes(java.lang.Integer likes) {
		set("likes", likes);
		return (M)this;
	}
	
	public java.lang.Integer getLikes() {
		return getInt("likes");
	}

	public M setCollectnum(java.lang.Integer collectnum) {
		set("collectnum", collectnum);
		return (M)this;
	}
	
	public java.lang.Integer getCollectnum() {
		return getInt("collectnum");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

	public M setUserid(java.lang.Integer userid) {
		set("userid", userid);
		return (M)this;
	}
	
	public java.lang.Integer getUserid() {
		return getInt("userid");
	}

	public M setPic(java.lang.String pic) {
		set("pic", pic);
		return (M)this;
	}
	
	public java.lang.String getPic() {
		return getStr("pic");
	}

	public M setText(java.lang.String text) {
		set("text", text);
		return (M)this;
	}
	
	public java.lang.String getText() {
		return getStr("text");
	}

	public M setCheatnum(java.lang.Integer cheatnum) {
		set("cheatnum", cheatnum);
		return (M)this;
	}
	
	public java.lang.Integer getCheatnum() {
		return getInt("cheatnum");
	}

	public M setSinger(java.lang.String singer) {
		set("singer", singer);
		return (M)this;
	}
	
	public java.lang.String getSinger() {
		return getStr("singer");
	}

}
