package com.ouran.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCheat<M extends BaseCheat<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setTopicDetialId(java.lang.Integer topicDetialId) {
		set("topic_detial_id", topicDetialId);
		return (M)this;
	}
	
	public java.lang.Integer getTopicDetialId() {
		return getInt("topic_detial_id");
	}

	public M setTuId(java.lang.Integer tuId) {
		set("tu_id", tuId);
		return (M)this;
	}
	
	public java.lang.Integer getTuId() {
		return getInt("tu_id");
	}

	public M setUser1id(java.lang.Integer user1id) {
		set("user1id", user1id);
		return (M)this;
	}
	
	public java.lang.Integer getUser1id() {
		return getInt("user1id");
	}

	public M setUser2id(java.lang.Integer user2id) {
		set("user2id", user2id);
		return (M)this;
	}
	
	public java.lang.Integer getUser2id() {
		return getInt("user2id");
	}

	public M setText(java.lang.String text) {
		set("text", text);
		return (M)this;
	}
	
	public java.lang.String getText() {
		return getStr("text");
	}

}
