package com.ouran.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseForward<M extends BaseForward<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setTuwenid(java.lang.Integer tuwenid) {
		set("tuwenid", tuwenid);
		return (M)this;
	}
	
	public java.lang.Integer getTuwenid() {
		return getInt("tuwenid");
	}

	public M setTopicdetialid(java.lang.Integer topicdetialid) {
		set("topicdetialid", topicdetialid);
		return (M)this;
	}
	
	public java.lang.Integer getTopicdetialid() {
		return getInt("topicdetialid");
	}

	public M setUserid(java.lang.Integer userid) {
		set("userid", userid);
		return (M)this;
	}
	
	public java.lang.Integer getUserid() {
		return getInt("userid");
	}

	public M setCheatid(java.lang.Integer cheatid) {
		set("cheatid", cheatid);
		return (M)this;
	}
	
	public java.lang.Integer getCheatid() {
		return getInt("cheatid");
	}

	public M setMusicid(java.lang.Integer musicid) {
		set("musicid", musicid);
		return (M)this;
	}
	
	public java.lang.Integer getMusicid() {
		return getInt("musicid");
	}

}
