package com.ouran.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCollect<M extends BaseCollect<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUserid(java.lang.Integer userid) {
		set("userid", userid);
		return (M)this;
	}
	
	public java.lang.Integer getUserid() {
		return getInt("userid");
	}

	public M setTuwenid(java.lang.Integer tuwenid) {
		set("tuwenid", tuwenid);
		return (M)this;
	}
	
	public java.lang.Integer getTuwenid() {
		return getInt("tuwenid");
	}

	public M setMusicid(java.lang.Integer musicid) {
		set("musicid", musicid);
		return (M)this;
	}
	
	public java.lang.Integer getMusicid() {
		return getInt("musicid");
	}

	public M setTopicdetial(java.lang.Integer topicdetial) {
		set("topicdetial", topicdetial);
		return (M)this;
	}
	
	public java.lang.Integer getTopicdetial() {
		return getInt("topicdetial");
	}

}
