package com.ouran.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTopicDetial<M extends BaseTopicDetial<M>> extends Model<M> implements IBean {

	public M setTopicid(java.lang.Integer topicid) {
		set("topicid", topicid);
		return (M)this;
	}
	
	public java.lang.Integer getTopicid() {
		return getInt("topicid");
	}

	public M setUserid(java.lang.Integer userid) {
		set("userid", userid);
		return (M)this;
	}
	
	public java.lang.Integer getUserid() {
		return getInt("userid");
	}

	public M setLikes(java.lang.Integer likes) {
		set("likes", likes);
		return (M)this;
	}
	
	public java.lang.Integer getLikes() {
		return getInt("likes");
	}

	public M setText(java.lang.String text) {
		set("text", text);
		return (M)this;
	}
	
	public java.lang.String getText() {
		return getStr("text");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

}
