package com.ouran.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("cheat", "id", Cheat.class);
		arp.addMapping("collect", "id", Collect.class);
		// Composite Primary Key order: followerid,userid
		arp.addMapping("follow", "followerid,userid", Follow.class);
		arp.addMapping("forward", "id", Forward.class);
		arp.addMapping("likes", "id", Likes.class);
		arp.addMapping("music", "id", Music.class);
		arp.addMapping("topic", "id", Topic.class);
		arp.addMapping("topic_detial", "id", TopicDetial.class);
		arp.addMapping("tuwen", "id", Tuwen.class);
		arp.addMapping("types", "id", Types.class);
		arp.addMapping("user", "id", User.class);
		arp.addMapping("wenji", "id", Wenji.class);
		arp.addMapping("wenji_detail", "id", WenjiDetail.class);
	}
}

