package com.ouran.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("cheat", "id", Cheat.class);
		// Composite Primary Key order: fenid,userid
		arp.addMapping("fen", "fenid,userid", Fen.class);
		// Composite Primary Key order: followerid,userid
		arp.addMapping("follow", "followerid,userid", Follow.class);
		arp.addMapping("likes", "id", Likes.class);
		arp.addMapping("topic", "id", Topic.class);
		// Composite Primary Key order: topicid,userid
		arp.addMapping("topic_detial", "topicid,userid", TopicDetial.class);
		arp.addMapping("tuwen", "id", Tuwen.class);
		arp.addMapping("types", "type", Types.class);
		arp.addMapping("user", "id", User.class);
		arp.addMapping("wenji", "id", Wenji.class);
		arp.addMapping("wenji_detail", "wenjiid", WenjiDetail.class);
	}
}

