package com.ouran.model;

import com.ouran.model.base.BaseCheat;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cheat extends BaseCheat<Cheat> {
	public static final Cheat dao = new Cheat().dao();
}
