package com.ouran.model;

import com.ouran.model.base.BaseFen;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Fen extends BaseFen<Fen> {
	public static final Fen dao = new Fen().dao();
}
