package com.ouran.model;

import com.ouran.model.base.BaseForward;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Forward extends BaseForward<Forward> {
	public static final Forward dao = new Forward().dao();
}
