package com.ouran.model;

import com.ouran.model.base.BaseLikes;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Likes extends BaseLikes<Likes> {
	public static final Likes dao = new Likes().dao();
}
