package com.ouran.model;

import com.ouran.model.base.BaseMusic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Music extends BaseMusic<Music> {
	public static final Music dao = new Music().dao();
}
