package com.ouran.model;

import com.ouran.model.base.BaseTopicDetial;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TopicDetial extends BaseTopicDetial<TopicDetial> {
	public static final TopicDetial dao = new TopicDetial().dao();
}
