package com.ouran.model;

import com.ouran.model.base.BaseTuwen;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tuwen extends BaseTuwen<Tuwen> {
	public static final Tuwen dao = new Tuwen().dao();
}
