package com.ouran.model;

import com.ouran.model.base.BaseTypes;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Types extends BaseTypes<Types> {
	public static final Types dao = new Types().dao();
}
