package com.ouran.model;

import com.ouran.model.base.BaseWenjiDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WenjiDetail extends BaseWenjiDetail<WenjiDetail> {
	public static final WenjiDetail dao = new WenjiDetail().dao();
}
