package com.ouran.model;

import com.ouran.model.base.BaseWenji;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Wenji extends BaseWenji<Wenji> {
	public static final Wenji dao = new Wenji().dao();
}
