# tomcat
server:
  port: 8888
  servlet:
    context-path: /ouranbook

# spring
spring:
  # mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ouran_db?useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
  # mvc.view
  mvc:
    view:
      prefix: /
      suffix: .jsp

# mybatis
mybatis:
  #  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  configuration: # 指定mybatis全局配置文件中的相关配置项
    # 开启mybatis驼峰命名法转换
    map-underscore-to-camel-case: true